Mohamed and Praises
MohamedCK/My-Portfolio-Website pull request #18
Opened 2022-07-21 15:12 UTC by MohamedCK

##Popup Cards

- You should implement the following interactions:
   - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
     - When the user clicks (or taps) the close (X) button, the popup disappears.
- You should implement popups for both mobile and desktop screen sizes

2022-07-21 16:56 UTC, Nemwel-Boniface requested changes
## Hello @MohamedCK           :wave: , 

I'm Nemwel your reviewer for this PR :man_beard: 

You  have done a great job setting your portfolio modal popup it looks very professional :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 16:56 UTC, Nemwel-Boniface commented on popup.js
> +  // document.querySelector('.model .button-list').innerHTML = listButton (popup, work);
- [x] Kindly note that according to the javascript [best practices for the browser](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) number 7, You are supposed to remove all commented and unwanted code from your code base as it makes it cluttered and messy. Kindly make sure that you remove them from your code base.

2022-07-21 16:56 UTC, Nemwel-Boniface commented on popup.css
> +.model {
- [ ] Great job styling your modal popup it looks really good. However, kindly note that you are supposed to stick as much as possible to the chosen Figma design. Currently, your modal popup for desktop is fixed at the bottom side of the screen and it is supposed to be placed on the middle side of the screen. Kindly fix this.

**This is how your design currently loos like:**

![image](https://user-images.githubusercontent.com/86318284/180270409-316897c3-e920-46a5-a268-b141a5d99acd.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/180270589-82171c15-4aa1-4205-9e5d-b9191faa0648.png)

2022-07-21 18:11 UTC, 1GORDON requested changes
##
## Hi @MohamedCK & @PraisesPJMT ✋

Good job so far!

## Highlights!
- Followed Git flow ✔️ 
- Good commit messages ✔️
- Descriptive Pull Request ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions

- [x] [Optional] You may kindly remove the `locals.js` file from your project as the file is blank and not necessary for now.
- [ ] [Optional] You may also use the correct [Readme file template](https://github.com/microverseinc/readme-template) and customize it accordingly. the template you used is different from the one provided in the general requirements.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._** 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 18:11 UTC, 1GORDON commented on popup.css
> +    /* height: 50%; */
Great job team 🤝

- [ ] [Optional] You may kindly remove all commented code from your style sheets. This is not regarded as a good practice.

2022-07-21 18:11 UTC, 1GORDON commented on popup.css
> +  }
Great job @MohamedCK & @PraisesPJMT 🤝

- [ ] Just like the previous reviewer pointed out, you may kindly fix the popup on both mobile and desktop designs. Your popups are both fixed to the bottom. You cold add `margin-botton` to your popups.
- Your mobile popup
![mobile popup](https://user-images.githubusercontent.com/63917725/180281878-f2ae148d-e2f0-4d7c-918e-39c11511fc7b.PNG)

- Your desktop popup
![desktop popup](https://user-images.githubusercontent.com/63917725/180282050-0b2e4ff0-78ae-4a46-9885-061211d84361.PNG)

2022-07-22 09:09 UTC, topeogunleye approved these changes
### Hi Team, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 10:40 UTC, merged